title: <p align="center"> Cristian Rodriguez</p>

logo: "/images/image.jpg?raw=true"

description:
  <p align="center">
  <a href="https://www.kaggle.com/crprpr/account">Kaggle</a> |
  <a href="https://www.linkedin.com/in/cristian-rodriguez-546a4150">LinkedIn</a> |
  <a href="https://github.com/script32">GitHub</a>
  </p>
  
  <p align="justify">
  Actualmente me encuentro cursando un MBA en Global School con titulacion en la Universidad de Barcelona.
  <br><br>
  Tengo una larga trayectoria en el Sector Utility, especificamente en Generacion, Transmision, Distribucion y Comercializacion. Llevando proyectos desde la Digitalizacion hasta Inteligencia Artificia. Tambien tengo nivel de Desarrollador FullStack nivel Senior.
  <br><br>
  </p>
  <img src="images/Skills.png"/>
  
theme: jekyll-theme-minimal
google_analytics: G-J177QW16XN # Google Analytics tracking ID
