title: <p align="center"> Cristian Rodriguez</p>

logo: "/images/image.jpg?raw=true"

description:
  <p align="center">
  <a href="https://www.kaggle.com/crprpr/account">Kaggle</a> |
  <a href="https://www.linkedin.com/in/cristian-rodriguez-546a4150">LinkedIn</a> |
  <a href="https://github.com/script32">GitHub</a>
  </p>
  
  <p align="justify">
  Me considero una persona pragmática y proactiva, esto a lo largo de mi trayectoria me ha llevado a ir superando las barreras del conocimiento, no solo la parte tecnología la cual tengo 17 años de experiencia, sino la parte de los negocios, me llevo a titularme de master en global MBA, lo cual me permite entender de forma mas profunda las necesidades de los negocios, buscando mejor experiencia de los clientes o aumentar el nivel de digitalización de las empresas.
  <br><br>
  Tengo una larga trayectoria en el Sector Utility, especificamente en Generacion, Transmision, Distribucion y Comercializacion. Llevando proyectos desde la Digitalizacion hasta Inteligencia Artificia. Tambien tengo nivel de Desarrollador FullStack nivel Senior.
  <br><br>
  </p>

  
theme: jekyll-theme-minimal
google_analytics: G-J177QW16XN # Google Analytics tracking ID
