title: <p align="center"> Cristian Rodriguez</p>

logo: "/images/image.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/cristian-rodriguez-546a4150">LinkedIn</a> |
  <a href="https://github.com/script32">GitHub</a>
  </p>
  
  <p align="justify">
  Actualmente me encuentro cursando un MBA en Global School con titulacion en la Universidad de Barcelona.
  <br><br>
  Tengo mas 16 de experiencia en el Sector Utility, especificamente en Generacion, Transmision, Distribucion y Comercializacion. Llevando proyectos desde la Digitalizacion hasta Inteligencia Artificia. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
